const TrekPages = [
    {
        id: 1, name: "Mardi Himal Trek",
        desc: "The Mardi Himal Trek is a lesser-known trek in the Annapurna region of Nepal that offers a unique and challenging adventure for trekkers. The trail takes you through lush rhododendron forests, terraced fields, and traditional villages, offering a chance to experience the local culture and lifestyle of the Gurung people. The trek is relatively short, taking 5-7 days to complete, but it is considered to be a moderate to difficult level trek due to the rugged terrain and high altitude.\nOne of the main highlights of the trek is the breathtaking views of the Himalayas, including the famous Annapurna and Dhaulagiri ranges. The trail reaches a maximum altitude of 4,500 meters, providing trekkers with a chance to witness some of the most beautiful mountain landscapes in the world. The trek is best done between September and November or March and May, as the weather is more favorable during these months.\nThe Mardi Himal trek is an ideal option for those looking for a challenging and off-the-beaten-path experience in the Himalayas. It is a perfect blend of natural beauty, cultural richness and adventure. It is a great opportunity to explore the remote and lesser-visited areas of Nepal and experience the diverse flora and fauna that the region has to offer. The trek is suitable for experienced trekkers who are in good physical condition, but it is also accessible to those who are relatively new to trekking as long as they are well-prepared.",
        image: "./images/popular/mardi_base.jpeg"
    },
    {
        id: 2, name: "Annapurna Trekking", 
        desc: "The Annapurna Trek is one of the most popular trekking routes in Nepal and offers a diverse range of landscapes, culture and adventure. The trek takes you through lush forests, traditional villages, and terraced fields, providing a chance to experience the local lifestyle and culture of the Gurung and Magar people. The trek also offers a glimpse of the Annapurna and Dhaulagiri mountain ranges, which are some of the most beautiful mountain landscapes in the world. The trek can take anywhere from 7 to 21 days depending on the route chosen and the trekker's fitness level.\nThe Annapurna Trek offers a variety of options, from easy to strenuous treks, that cater to different levels of trekkers. The most popular route is the Annapurna Circuit trek, which takes around 12-21 days, and is considered a moderate to difficult level trek. The trek takes you through remote and rugged terrain, reaching a maximum altitude of 5,416 meters, the Thorong La Pass, which is considered one of the most challenging passes in the Himalayas. The trek is best done between September and November or March and May, as the weather is more favorable during these months.\nThe Annapurna trek is a great opportunity to explore the remote and lesser-visited areas of Nepal and experience the diverse flora and fauna that the region has to offer. The trek is suitable for experienced trekkers who are in good physical condition, but it is also accessible to those who are relatively new to trekking as long as they are well-prepared. The Annapurna trek offers a unique and unforgettable experience with a chance to witness some of the most beautiful mountain landscapes in the world, and explore the rich culture and lifestyle of the local people.",
        image: "./images/popular/annapurna_base.jpg"
    },
    {
        id: 3, name: "Everest Trekking",
        desc: "The Everest Trek, also known as the Khumbu Trek, is a popular trekking route in Nepal that takes you to the base camp of the world's highest mountain, Mount Everest. The trek offers a chance to explore the local culture and lifestyle of the Sherpa people and witness the stunning Himalayan landscapes. The trek can take anywhere from 12 to 20 days depending on the route chosen and the trekker's fitness level.\nThe most popular route for the Everest Trek is the classic Everest Base Camp Trek, which takes around 12-16 days, and is considered a moderate to difficult level trek. The trek takes you through remote and rugged terrain, reaching a maximum altitude of 5,364 meters, the Base Camp of Mount Everest. The trek is best done between September and November or March and May, as the weather is more favorable during these months. Along the trail, you will have the opportunity to visit traditional Sherpa villages, monasteries, and experience the unique culture of the Sherpa people.\nThe Everest Trek is a challenging but rewarding experience, providing trekkers with a chance to witness some of the most beautiful mountain landscapes in the world, and explore the rich culture and lifestyle of the local people. It is suitable for experienced trekkers who are in good physical condition, but it is also accessible to those who are relatively new to trekking as long as they are well-prepared. The trek provides an opportunity to experience the remote and lesser-visited areas of Nepal and to discover the natural and cultural heritage of the Khumbu region.",
        image: "./images/popular/everest_base_trekking.jpg"
    },
    {
        id: 4, name: "Manaslu Trekking",
        desc: "The Manaslu Trek is a remote and off-the-beaten-path trekking route in Nepal that takes you through the beautiful and remote landscapes of the Manaslu region. The trek offers a chance to experience the local culture and lifestyle of the Tibetan-origin people and witness the stunning mountain landscapes of the Himalayas. The trek can take anywhere from 8 to 14 days depending on the route chosen and the trekker's fitness level.\nThe Manaslu Trek is a challenging but rewarding experience, providing trekkers with a chance to witness some of the most beautiful and remote mountain landscapes in Nepal. The trek takes you through remote and rugged terrain, reaching a maximum altitude of 5,106 meters, the Larkya La Pass. The trek is best done between September and November or March and May, as the weather is more favorable during these months. Along the trail, you will have the opportunity to visit traditional villages, explore the diverse flora and fauna and experience the unique culture of the local people.\nThe Manaslu trek is a perfect option for those looking for a challenging and off-the-beaten-path experience in the Himalayas. It is less crowded compared to other popular treks in Nepal, and offers an opportunity to explore the remote and lesser-visited areas of the country. The trek is suitable for experienced trekkers who are in good physical condition, but it is also accessible to those who are relatively new to trekking as long as they are well-prepared. The trek provides an opportunity to experience the natural and cultural heritage of the region and discover the unique culture of the Tibetan-origin people.",
        image: "./images/popular/manaslu_cir.jpg"
    },
    {
        id: 5, name: "PoonHill Trekking",
        desc: "The Poon Hill Trek is a popular and relatively easy trekking route in Nepal that takes you to the famous viewpoint of Poon Hill. The trek offers stunning views of the Annapurna and Dhaulagiri mountain ranges, and a chance to experience the local culture and lifestyle of the Gurung people. The trek can take anywhere from 3 to 5 days depending on the route chosen and the trekker's fitness level.\nThe Poon Hill Trek is a great option for those who have limited time and are looking for a relatively easy trek that still provides stunning mountain views. The trek takes you through lush rhododendron forests, terraced fields, and traditional villages, and reaches a maximum altitude of 3,210 meters, the Poon Hill viewpoint. The trek is best done between September and November or March and May, as the weather is more favorable during these months. Along the trail, you will have the opportunity to visit traditional villages, and experience the unique culture of the local people.\nThe Poon Hill trek is suitable for trekkers of all ages and fitness levels, and it is a perfect option for those who are looking for a short and easy trek that still provides stunning mountain views. It is a great opportunity to explore the remote and lesser-visited areas of Nepal and experience the diverse flora and fauna that the region has to offer. The trek provides an opportunity to experience the natural and cultural heritage of the region and discover the unique culture of the local people.",
        image: "./images/popular/poonhill.jpeg"
    },
]

export default TrekPages;